#!/bin/sh
alias aliases='vim-if-not-emacs ~/.aliases.sh'
alias c='clear'
alias dots='vim-if-not-emacs ~/.config/homer/dotfiles.dots'
alias gjh='cd ~/code/github/joshuaharry'
alias gp='cd $(cat ~/.config/emacs/current-project)'
alias gubuntu='docker run --rm -it --entrypoint fish ubuntu'
alias l='exa -l'
alias lh='exa -l -a'
alias ls='exa -l'
alias nvim='vim-if-not-emacs'
alias reload='unalias -a && . "$HOME"/.aliases.sh'
alias rimraf='rm -rf'
alias sc='pwd > ~/.config/emacs/current-project'
alias v='vim-if-not-emacs'
alias vi='vim-if-not-emacs'
alias vim='vim-if-not-emacs'
alias vimrc='vim-if-not-emacs ~/.config/nvim/init.lua'
